import 'dart:io';

import 'package:http/http.dart' as http;

/// Tool to generate device_name dart code

const fileName = "case_ret.g.dart";

void main() async {
  // Go [https://gist.github.com/adamawolf/3048717] get newest Raw file url like this:
  // [https://gist.githubusercontent.com/adamawolf/3048717/raw/a956ed1552091c32ce9f9f39e2210cc6359b9b26/Apple_mobile_device_types.txt]
  final uri = Uri.parse("https://gist.githubusercontent.com/adamawolf/3048717/raw/a956ed1552091c32ce9f9f39e2210cc6359b9b26/Apple_mobile_device_types.txt");
  // Get uri
  var response = await http.get(uri);
  final lines = response.body.split("\n");

  // Start write to file
  final stringBuffer = StringBuffer();
  stringBuffer.write("""
/// This file is automatically generated. DO NOT EDIT, all your changes would be lost.
/// Copy the result below to device_name.dart. Author: hwh97

String? ios(String? machine) {
  switch (machine) {
""");
  for (String line in lines) {
    if (line.trim().isEmpty) {
      // Insert new line
      stringBuffer.writeln("");
      continue;
    }
    final content = line.split(":");
    if (content.length < 2) {
      // Skip it if length less then 2
      continue;
    }
    stringBuffer.write("""
    case '${content[0].trim()}':
      return '${content[1].trim()}';
""");
  }
  stringBuffer.write("""
  }
}
""");
  File("lib/$fileName").writeAsStringSync(stringBuffer.toString());
  print("Generated successfully");
}